- choco-solver/src/main/java/org/chocosolver/memory/structure/IndexedBipartiteSet.java
For example:
```java
public static void main(String[] args) {
Solver s = new Solver();
IndexedBipartiteSet i = new IndexedBipartiteSet(s.getEnvironment(), new int[]{12, 13});
if (i.contains(6)) {
System.out.println(i.pretty() + " contains 6");
}
}
```
The above code will print "[12, 13] contains 6".
> Fix IndexedBipartiteSet.

- choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/count/PropCountVar.java
- choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/count/PropCount_AC.java
1. Fixed bug which caused duplicate output of last var (cardinality) if where are less than 3 items in decvars.
2. Added separate output of cardinality and restricted value.
> Improve toString of count constraints.

- choco-solver/src/main/java/org/chocosolver/solver/search/loop/ISearchLoop.java
- choco-solver/src/main/java/org/chocosolver/solver/search/loop/SearchLoop.java
- choco-solver/src/main/java/org/chocosolver/solver/search/loop/lns/LargeNeighborhoodSearch.java
- modify ISearchLoop.interrupt(), add new parameter 'avoidable' to qualify the strength of the interruption
> Issues #304:

- src/main/java/org/chocosolver/solver/Solution.java
- src/main/java/org/chocosolver/solver/variables/IVariableFactory.java
- src/main/java/org/chocosolver/solver/variables/SetVar.java
- src/main/java/org/chocosolver/solver/variables/impl/SetVarImpl.java
- src/test/java/org/chocosolver/solver/variables/impl/SetVarImplTest.java
- added SetVarImpl. getCard() and setCard(IntVar)
- added corresponding simple test
- specified setVar(String name, int... values) instead  of setVar(String name, int[] value) with null test on values
> Set var.card

- src/main/java/org/chocosolver/solver/constraints/ISetConstraintFactory.java
- src/test/java/org/chocosolver/solver/constraints/set/CardinalityTest.java
- src/test/java/org/chocosolver/solver/propagation/DeltaTest.java
- src/test/java/org/chocosolver/solver/search/TestMultiSequentialObjectives.java
- src/test/java/org/chocosolver/solver/variables/impl/SetVarImplTest.java
and use SetVar.getCard() or SetVar.setCard() instead.
> remove cardinality constraint

- src/main/java/org/chocosolver/solver/Solution.java
For example:
```java
public static void main(String[] args) {
Model model = new Model();
IntVar a = model.intVar("a", 1);
Solution solution = model.getSolver().findSolution();
System.out.println(solution.getIntVal(a));
}
```
This will throw a null pointer exception.
> Check map if null.

- src/main/java/org/chocosolver/solver/Solver.java
The thread is now cached in a local variable.
> Close #521.

- src/sphinx/source/3_solving.rst
Minor correction in documentation.
> Use correct function name printStatistics

- src/sphinx/source/3_solving.rst
> Missing word

- src/main/java/org/chocosolver/solver/constraints/IIntConstraintFactory.java
Hi,
Just ran across a few minor typos while browsing the documentation.
- correction to notAllEqual and or javadocs
> Fix doc for notAllEqual and or constraints

- src/main/java/org/chocosolver/solver/variables/impl/AbstractVariable.java
- src/main/java/org/chocosolver/solver/variables/impl/BitsetArrayIntVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/BitsetIntVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/BoolVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/FixedBoolVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/FixedIntVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/FixedRealVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/IntervalIntVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/RealVarImpl.java
- src/main/java/org/chocosolver/solver/variables/impl/SetVarImpl.java
- src/main/java/org/chocosolver/solver/variables/view/BoolNotView.java
- src/main/java/org/chocosolver/solver/variables/view/MinusView.java
- src/main/java/org/chocosolver/solver/variables/view/OffsetView.java
- src/main/java/org/chocosolver/solver/variables/view/RealView.java
- src/main/java/org/chocosolver/solver/variables/view/ScaleView.java
See https://github.com/chocoteam/choco-solver/pull/598 for motivations.
> Add createScheduler in AbstractVariable for constructor for extensions compatibility.

- .travis.yml
- src/main/java/org/chocosolver/solver/search/loop/lns/neighbors/INeighbor.java
- src/main/java/org/chocosolver/solver/search/loop/lns/neighbors/SetRandomNeighbor.java
- src/test/java/org/chocosolver/solver/expression/continuous/ExpressionTest.java
- Fix the ibex tests
- turn on 1s and 10s test groups in travis (ibex is already turned on in the target branch)
- Fix minor comments by codacy-bot in existing ineighbor-pull-request
> Fix ibex tests

- src/sphinx/source/3_solving.rst
Fixes #625.
- Fixes the documentation by removing the mention to printDecisions() and replacing it by showDecisions()
> fix documentation (issue 625)

- src/main/java/org/chocosolver/solver/Solution.java
- src/test/java/org/chocosolver/solver/SolutionTest.java
This fixes issue #627.
Fixes # .
- 
- 
- 
> Fix copying of empty solutions

- examples/src/main/java/org/chocosolver/examples/integer/AirPlaneLanding.java
- examples/src/main/java/org/chocosolver/examples/integer/RLFAP.java
- examples/src/main/java/org/chocosolver/examples/real/Grocery.java
- parsers/src/main/java/org/chocosolver/database/MySQLAccess.java
- parsers/src/main/java/org/chocosolver/parser/Parser.java
- parsers/src/main/java/org/chocosolver/parser/RegParser.java
- parsers/src/main/java/org/chocosolver/parser/flatzinc/Flatzinc.java
- parsers/src/main/java/org/chocosolver/parser/mps/MPSParser.java
- parsers/src/main/java/org/chocosolver/parser/xcsp/XCSPParser.java
> Fix LGTM alerts

- CHANGES.md
- solver/src/main/java/org/chocosolver/solver/QuickXPlain.java
- solver/src/main/java/org/chocosolver/solver/Solver.java
- solver/src/main/java/org/chocosolver/solver/constraints/Constraint.java
- solver/src/main/java/org/chocosolver/solver/constraints/Propagator.java
- solver/src/test/java/org/chocosolver/solver/constraints/ConstraintTest.java
- solver/src/test/java/org/chocosolver/solver/constraints/checker/QuickXPlainTest.java
I'm proposing this PR @cprudhom so that you will be able to better evaluate what we were talking about in gitter.
- Add a QuickXPlain algorithm to find the minimum conflicting set of constraints (ISSUE #509)
- Add support to disable constraints from execution (this feature is also required for QuickXPlain)
> Quick xplain proposal

- solver/src/main/java/org/chocosolver/solver/variables/view/BoolNotView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/EqView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/GraphNodeSetView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/GraphPredecessorsSetView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/GraphSetView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/GraphSuccessorsSetView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/IView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/IntBoolView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/IntView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/LeqView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/MinusView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/OffsetView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/RealView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/ScaleView.java
Fixes # .
- Make views generic
> Generify views

- solver/src/test/java/org/chocosolver/solver/constraints/graph/cost/hcp/HamiltonianCycleProblem.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/cost/hcp/KnightTourProblem.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/cost/trees/DcmtsTest.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/cost/tsp/TspTest.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/symmbreaking/SymmetryBreaking2Test.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/symmbreaking/SymmetryBreaking3Test.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/symmbreaking/SymmetryBreakingDirectedTest.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/symmbreaking/SymmetryBreakingTest.java
Fixes # .
- Specify groups in costs and symmbreaking graph constraints tests to include them in CI.
> Add groups to costs and symmbreaking graph constraint tests

- solver/src/main/java/org/chocosolver/solver/constraints/graph/connectivity/PropConnected.java
- solver/src/main/java/org/chocosolver/solver/constraints/graph/connectivity/PropNbCC.java
- solver/src/main/java/org/chocosolver/util/graphOperations/connectivity/UGVarConnectivityHelper.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/connectivity/ConnectedTest.java
- solver/src/test/java/org/chocosolver/solver/constraints/graph/connectivity/NbConnectedComponentsTest.java
Fix articulation points and bridge linking mandatory nodes detection
Thanks @dimitri-justeau for the test suite!
> fix connected et nbCC

- solver/src/main/java/org/chocosolver/solver/variables/impl/BoolVarImpl.java
- solver/src/main/java/org/chocosolver/solver/variables/impl/IntervalIntVarImpl.java
- solver/src/main/java/org/chocosolver/solver/variables/view/BoolIntView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/bool/BoolNotView.java
- solver/src/main/java/org/chocosolver/solver/variables/view/bool/BoolSetView.java
- solver/src/test/java/org/chocosolver/solver/variables/BoolNotViewTest.java
- solver/src/test/java/org/chocosolver/solver/variables/ViewMinusTest.java
- solver/src/test/java/org/chocosolver/solver/variables/ViewsTest.java
- solver/src/test/java/org/chocosolver/solver/variables/fast/BitsetArrayIntVarImplTest.java
- solver/src/test/java/org/chocosolver/solver/variables/fast/BitsetIntVarImplTest.java
- solver/src/test/java/org/chocosolver/solver/variables/fast/IntervalIntVarImplTest.java
- solver/src/test/java/org/chocosolver/solver/variables/impl/BoolVarImplTest.java
- solver/src/test/java/org/chocosolver/solver/variables/impl/IntVarIntMinusViewTest.java
- solver/src/test/java/org/chocosolver/solver/variables/impl/IntVarOffSetViewTest.java
- solver/src/test/java/org/chocosolver/solver/variables/view/BoolEqViewTest.java
- solver/src/test/java/org/chocosolver/solver/variables/view/BoolLeqViewTest.java
It was possible to obtain LB > UB without contradiction using IntervalIntVarImpl.updateBounds
> fix update bounds

- solver/src/main/java/org/chocosolver/solver/variables/impl/AbstractVariable.java
should speedup the usage of variables within sets and maps
> implement equals and hashcode based on ID

- solver/src/main/java/org/chocosolver/solver/objective/ParetoMaximizer.java
> Optimize computeTightestPoint & propagate in ParetoMaximizer - fixes #1026

- solver/src/main/java/org/chocosolver/solver/constraints/IIntConstraintFactory.java
- solver/src/main/java/org/chocosolver/solver/expression/discrete/arithmetic/BiArExpression.java
- solver/src/main/java/org/chocosolver/solver/expression/discrete/arithmetic/UnArExpression.java
the constraint logic should be in the constraint factory only
> pow and square refactoring
