choco-solver/src/main/java/org/chocosolver/solver/constraints/binary/PropLessOrEqualXY_C.java
For example, the following code should find 3 solutions but currently finds none.
```java
Solver s = new Solver();
IntVar i = VF.enumerated("i", -1, 1, s);
IntVar j = VF.enumerated("j", -1, 1, s);
s.post(ICF.arithm(j, "+", i, "<", 1));
LCF.ifThen(ICF.arithm(i, "=", -1), ICF.arithm(i, "!=", -1));
s.set(ISF.lexico_UB(j, i));
Chatterbox.showDecisions(s);
Chatterbox.showSolutions(s);
Chatterbox.showContradiction(s);
ExplanationFactory.CBJ.plugin(s, true, false);
System.out.println(s.findAllSolutions());
```
=> Fixed PropLessOrEqualXY_C to add the right rule.

choco-solver/src/main/java/org/chocosolver/solver/variables/impl/BitsetArrayIntVarImpl.java
For example:
```java
public static void main(String[] args) throws Exception {
Solver s = new Solver();
IntVar i = VF.enumerated("i", new int[]{0,98,99}, s);
IIntDeltaMonitor d= i.monitorDelta(Cause.Null);
i.updateUpperBound(98, Cause.Null);
d.freeze();
d.forEachRemVal((IntProcedure) System.out::println);
d.unfreeze();
}
```
This will print "99 98 0" even though the only removed value is 99.
=> Fixed BitsetArrayIntVarImpl::updateUpperBound adding spurious values to its delta

choco-solver/src/main/java/org/chocosolver/solver/constraints/binary/PropScale.java
1. This propagator is only correct if y has a positive value, reintroduced the assertion removed in previous commit.
2. Use MathUtils.divFloor and MathUtils.divCeil for readability and performance.
=> Two minor changes to PropScale.

src/main/java/org/chocosolver/solver/search/strategy/SearchStrategyFactory.java, src/main/java/org/chocosolver/solver/search/strategy/selectors/VarSelectorFactory.java, src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/FirstFail.java, src/test/java/org/chocosolver/samples/todo/problems/integer/KnightTourProblem_Circuit.java, src/test/java/org/chocosolver/solver/explanations/ExplanationEngineTest.java, src/test/java/org/chocosolver/solver/search/StrategyTest.java
I got some performance issues when having tons of variables.
This is a port of my own FirstFail that provided the following optimisations:
- Add a shortcut to stop at the moment we have a variable with a domain size of 2
- store the loop offset
Performance  improvement on my code:
```
Vanilla FirstFail: After 66897ms of search (terminated): 6439 opened search node(s), 1817 backtrack(s), 1 solution(s):
New FirstFail: After 55937ms of search (terminated): 6439 opened search node(s), 1817 backtrack(s), 1 solution(s):
```
=> Improve FirstFail

src/main/java/org/chocosolver/solver/Solver.java
Minimal change in develop branch to support Thread.interrupt() method used by thread pools to end a thread since method Thread.stop() is deprecated.
Maybe extra property of Solver class may be created to know whether a solver was stopped thanks to interrupted thread or some stop criteria was met.
=> when a thread used by choco solver is interrupted by Thread.interrupt() method, the solver should be stopped

src/main/java/org/chocosolver/solver/Solution.java
I use a lot of channeling constraints and only use one of the variables in the search strategy, but I would still like to query the values of the other variable.
For example:
```java
public static void main(String[] args) {
Model model = new Model();
BoolVar[] bools = model.boolVarArray("bool", 2);
SetVar set = model.setVar("set", new int[]{}, new int[]{0,1});
model.setBoolsChanneling(bools, set).post();
Solver solver = model.getSolver();
solver.setSearch(Search.minDomLBSearch(bools));
Solution solution = solver.findSolution();
System.out.println(Arrays.toString(solution.getSetVal(set)));
}    
```
This will throw a null pointer exception because the value for "set" was never recorded.
=> Record all variables in a solution by default.

src/main/java/org/chocosolver/util/objects/setDataStructures/bitset/Set_BitSet.java, src/main/java/org/chocosolver/util/objects/setDataStructures/bitset/Set_Std_BitSet.java, src/main/java/org/chocosolver/util/objects/setDataStructures/constant/Set_FixedArray.java, src/main/java/org/chocosolver/util/objects/setDataStructures/linkedlist/Set_LinkedList.java, src/main/java/org/chocosolver/util/objects/setDataStructures/swapList/Set_Swap.java
The current implementation of toString calls iterator() which reuses the internal iterator. This means that toString cannot be used inside a loop of the set. For example:
```java
for (int i : set.getUB()) {
// Do not call set.toString nor set.getUB().toString(), otherwise it messes with the for loop.
// In addition, my preferred debugger uses toString to give human readable information, hence
// I cannot debug inside this loop.
}
```
Since toString is typically used for debugging, I think this PR is useful.
=> Change ISet::toString implementations to use newIterator(), rather than iterator()

src/main/java/org/chocosolver/solver/variables/view/ScaleView.java
Scale view allows instantiating to a value it does not contain. For example
```
public static void main(String[] args) throws Exception {
Model m = new Model();
IntVar i = m.intVar("i", 0, 4);
m.arithm(m.intScaleView(i, 10), "=", 11).post();
Solver s = m.getSolver();
while (s.solve()) {
System.out.println(i + " * 10 = 11");
}
}
```
This will find solutions (and fail the entailment check).
=> Fix scale view instantiation.

src/main/java/org/chocosolver/solver/constraints/ISetConstraintFactory.java, src/main/java/org/chocosolver/solver/constraints/set/PropIntersectionFilterSets.java, src/test/java/org/chocosolver/solver/constraints/set/IntersectionTest.java
This PR is with regards to issue #448.
I know in your message you said to specialize it for the binary case, but I need it for the n-ary case.
I've ran about a million fuzz tests for the intersection constraint. Based on these tests, I think PropIntersection and PropIntersectionFilterSets are both idempotent. In addition, I think the combination of these two propagators are bound consistent. I couldn't find a counterexample in the million fuzz tests.
=> A complementary intersection propagator for filtering the sets.

src/main/java/org/chocosolver/solver/constraints/set/PropElement.java
For example, the following code will throw an index out of bounds exception:
```java
public static void main(String[] args) {
Model model = new Model();
Constraint constraint = model.element(
model.intVar(-1),
new SetVar[]{model.setVar(1, 2, 3), model.setVar(2, 3, 4)},
model.setVar("set", new int[0], new int[]{0, 1, 2, 3, 4})
);
System.out.println(constraint.isSatisfied());
}
```
=> Fix PropElement::isEntailed index out of range exception.

src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/FirstFail.java
- Before: at least 3 tests per variable.
- After: at most 3 tests per variable.
=> optimize first fail variable selector

src/main/java/org/chocosolver/sat/PropNogoods.java
I would like to propose this pull request. In ASSIST, we are calling propagate after adding a set of constraints to check, if the problem is still solvable. Unfortunately, initialize() is only called as part of solve(), so our propagate() calls hit the assertion. We could fix this by lines:
[ASSISTSolver.xtend](https://github.com/RobertHilbrich/assist-public/blob/master/ch.hilbri.assist.mapping/src/ch/hilbri/assist/mapping/solver/AssistSolver.xtend) lines 90-92, but this is not good for readability.
=> Added minor patch for missing initialization when calling propagate() before solve()

pom.xml
Fixes N/A .
- Add an Automatic-Module-Name entry to the MANIFEST.MF in order to be able to use the project as a dependency in modularized projects
We are developing a Combinatorial Testing Framework at [coffee4j](https://github.com/coffee4j/coffee4j) and we're using Choco Solver as a dependency. We aim to modularize our project with Java 9 Modules introduced with [Project Jigsaw](https://openjdk.java.net/projects/jigsaw/).
While compiling maven gives us this error message:
```
***********************************************************************************************************************************************
* Required filename-based automodules detected: [choco-solver-4.10.0.jar]. Please don't publish this project to a public artifact repository! * …
```
=> Add stable module name

src/main/java/org/chocosolver/solver/Solver.java, src/main/java/org/chocosolver/solver/search/measure/MeasuresRecorder.java, src/test/java/org/chocosolver/solver/TestSolveur.java
Fixes #648 .
- Adds an `if` test in `Solver.isStopCriterionMet()` to avoid checking time stop criterion if the search is not started (this behaviour can happen after `Solver.hardReset()` )
=> solver time stop criterion returns true despite search not started after call to hardReset()

.lgtm.yml, solver/CHANGES.md, solver/src/main/java/org/chocosolver/solver/Solver.java, solver/src/test/java/org/chocosolver/solver/search/loop/SolverTest.java
Fixes # 659.
- Adding two methods in `Solver`, namely `moveForward(Decision)` and `moveBackward` to make possible applying a step-by-step search space exploration.
Example:
```java
Model model = new Model();                               
IntVar x1 = model.intVar("x1", 0, 2);                    
IntVar x2 = model.intVar("x2", 0, 2);                    
x1.eq(x2).post();                                        
Solver solver = model.getSolver();                       
IntStrategy strategy = inputOrderLBSearch(x1, x2);       
Decision<IntVar> dec = null;         
int sol = 0;                         
boolean search = true;               
while(search) {                      
if (solver.moveForward(dec)) {   
dec = strategy.getDecision();
if (dec == null) { …
```
=> Fix issue #659

solver/src/main/java/org/chocosolver/solver/constraints/ternary/PropMaxBC.java, solver/src/main/java/org/chocosolver/solver/constraints/ternary/PropMinBC.java
Remove code from PropMaxBC and PropMinBC: the code was correct but this version is easiest to read and still correct.
=> Cpru min max

solver/src/main/java/org/chocosolver/solver/ParallelPortfolio.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/sat/NogoodStealer.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/sat/PropNogoods.java, solver/src/main/java/org/chocosolver/solver/search/loop/monitors/NogoodFromRestarts.java, solver/src/test/java/org/chocosolver/solver/PortFolioTest.java, solver/src/test/java/org/chocosolver/solver/constraints/nary/NogoodTest.java, solver/src/test/java/org/chocosolver/solver/constraints/nary/sat/PropNogoodsTest.java
Offer the possibility, when using a `ParallelPortfolio`, to steal no-goods from decision path of other models. The unique (strong) assumption is that all models are *equivalent* :
- each variable exists in all models, 
- each variable has the same ID in all models 
- each variable is declared at the same position in all models. 
When this option is on, any worker with a restart policy will extract a nogood on each restart, based on its decision path, **and** based on current decision path of other models in the portfolio.
=> Enable nogood stealing (on restart) for ParallelPortfolio

solver/src/main/java/org/chocosolver/solver/constraints/IIntConstraintFactory.java
The permutation argument reflects the sorted position (1 based) of the
i:th element in `vars`.
Fixes # .
- 
- 
- 
=> Correct the `keySort()` example

solver/src/main/java/org/chocosolver/util/iterators/IntVarValueIterator.java, solver/src/test/java/org/chocosolver/solver/variables/impl/BoolVarImplTest.java, solver/src/test/java/org/chocosolver/solver/variables/impl/IntVarTest.java
Fixes #681 .
- Make IntVarValueIterator next() method throw a NoSuchElementException when no next element
=> make IntVarValueIterator next() method throw a NoSuchElementException

solver/src/main/java/org/chocosolver/solver/search/IResolutionHelper.java
findOptimalSolutions and streamOptimalSolutions methods first find the optimal solution of a problem, then post an arithmetic constraint to the model to enumerate all optimal solutions. However, as they do not unpost this arithmetic constraint, the model ends modified after calling these methods. Although in most cases this will not be a problem, it can lead to very unexpected behaviours if one reuses a Model several times. Note that findLexOptimalSolution already avoids this behaviour.
Fixes # .
- 
- 
- 
=> Prevent find[stream]OptimalSolutions to modify the model after return

solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/BiCArExpression.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RealTest.java, solver/src/test/java/org/chocosolver/solver/expression/continuous/IbexTest.java
This changes proposes a handling for integer exponents of the continuous power function (#702). 
Fixes # .
- Changed `pow` function of `BiCArExpression` to identify integer exponents and create the right expression for ibex, where the exponent is declared as a constant.
- Create a test to simulate the scenario
- Fix broken other tests
=> Fix arithmetic bug with Ibex and power operator for integer exponents

solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/BiCArExpression.java, solver/src/main/java/org/chocosolver/solver/expression/continuous/arithmetic/UnCArExpression.java, solver/src/main/java/org/chocosolver/util/tools/VariableUtils.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RealBase.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RealCubicTest.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RealExponentTest.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RealNegativePowerTest.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RealSquareTest.java, solver/src/test/java/org/chocosolver/solver/constraints/real/RestTrigTest.java
I've been working with several ibex operations and I've found some inconsistencies.
The objective of this PR is three-fold:
1. To contribute with a test suite for several math cases
2. Improve the bounds calculation for power with negative constant exponent
3. Fix some bounds for `SIN`, `TAN`, `SINH` and `TANH`
I'm not sure why the previous boundaries for `SIN`, `TAN`, `SINH`, and `TANH` were defined that way, but I executed the whole test battery for the solver module and no tests were impacted by this change.
=> Add test suite and fix math expressions for ibex integration

parsers/src/test/java/org/chocosolver/flatzinc/PerformanceTest.java, parsers/src/test/resources/flatzinc/instances.csv
- best objective value was never read
- check objective before nb sols & nodes & fails in case we can find the same optimum faster
=> PARSER performance test : fix objective checking

solver/src/main/java/org/chocosolver/solver/constraints/IIntConstraintFactory.java
The call to getDomainUnion() is useless given
that PropAtLeastNValues and PropAtMostNValues
propagators are commented.
Possibly, this call was escaped by the compiler but
this is a better way to be sure.
=> Dead code removal in IIntConstraintFactory#nvalue().

solver/src/main/java/org/chocosolver/solver/constraints/Propagator.java
on Scala 3, the compiler seems to have some deep trouble with the fact that  the `compareTo` argument has no type arguments. Even though this is fine for Java and its type-erasure knowledge, Scala totally breaks. I propose the simple addition of the `V` type parameter just to make sure this does not happen. It should not occur any hurdle anywhere else in the code, I believe.
I've just cloned and tested my scala codebase with the simple change, and it has worked! So there's nos loss. I could not complete the real number tests of the choco test suite due to lack of time and experience with IBEX, but the other discrete tests all passed. 
I am sorry if the main branch was no the one to be patched. It is such an easy patch that I think it will be easy to propagate to the correct branches.
=> Patch `compareTo` in Propagator.java for correct scala support.

solver/src/main/java/org/chocosolver/solver/propagation/PropagationEngine.java, solver/src/main/java/org/chocosolver/solver/search/strategy/strategy/AbstractStrategy.java, solver/src/main/java/org/chocosolver/solver/search/strategy/strategy/MultiArmedBanditSequencer.java
Some strategies like ConflictOrderingSearch are composite and require to call computeDecision(Var) of another strategy. Such method currently has a protected visibility.
This works because ConflictOrderingSearch is in the same package as AbstractStrategy, but not if one define a similar strategy within a different project/package. Setting these methods visibility to public allow such developments.
=> Make computeDecision and makeIntDecision public

.github/workflows/benchmarking.yml, .github/workflows/maven-test.yml, solver/src/main/java/org/chocosolver/solver/constraints/binary/PropGreaterOrEqualX_Y.java, solver/src/main/java/org/chocosolver/solver/constraints/binary/PropGreaterOrEqualX_YC.java, solver/src/main/java/org/chocosolver/solver/constraints/binary/PropLessOrEqualXY_C.java, solver/src/main/java/org/chocosolver/solver/constraints/extension/nary/ValidityChecker.java, solver/src/main/java/org/chocosolver/solver/constraints/graph/cost/trees/lagrangian/KruskalMSTFinder.java, solver/src/main/java/org/chocosolver/solver/constraints/graph/cost/trees/lagrangian/KruskalMSTGAC.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/alldifferent/algo/AlgoAllDiffBC.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/DisjunctiveTaskIntervalFilter.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/PropCumulative.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/SweepHeiSortCumulFilter.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/knapsack/PropKnapsackKatriel01.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/sort/PropKeysorting.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/sum/PropSum.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/sum/PropSumBool.java, solver/src/main/java/org/chocosolver/solver/constraints/nary/sum/PropSumWithLong.java, solver/src/main/java/org/chocosolver/solver/constraints/real/PropScalarMixed.java, solver/src/main/java/org/chocosolver/solver/search/strategy/strategy/SetTimes.java, solver/src/main/java/org/chocosolver/solver/variables/events/IntEventType.java
In order to reduce the duration of the "mzn" test suite , because it is very unstable, I investigate objects creation during propagation and found out 2 memory leaks.
Once corrected, the `testThemAll` tests went from 5m30 to 4m30 on my machine (decrease of about 18%).
@fhermeni I also fixed a leak that you noticed.
=> Reduce object creation during propagation

solver/src/main/java/org/chocosolver/memory/structure/SparseBitSet.java, solver/src/test/java/org/chocosolver/memory/structure/SparseBitSetTest.java
This implementation for IStateBitSet targets backtrackable bitsets that mostly contains 0. For non-dense bitsets, this implementation is more efficient in terms of memory usage as bitsets are allocated per region instead of relying on a single, possibly bit array. In this context, the iteration is also faster.
=> SparseBitSet for a backtrackable bitset with mostly 0s.

solver/src/main/java/org/chocosolver/solver/variables/impl/BitsetArrayIntVarImpl.java, solver/src/main/java/org/chocosolver/solver/variables/impl/BitsetIntVarImpl.java, solver/src/main/java/org/chocosolver/solver/variables/view/IntView.java, solver/src/test/java/org/chocosolver/solver/variables/TaskTest.java
I had this pernicious bug that occurs when the `removeAllValuesBut` method is called from  for enumerated domain variables. This occurs when the variable is also monitored (here, a task) : the bounds was not up to date. Which led to inconcistency.
To fix the bug, I encapsulate the internal `updateBounds` call in a loop to make sure that side effects (monitors or views) are capture at the right time.
I also fix a bug in removeValues.
=> Fix bug in removeAllValuesBut and removeValues and for enumerated domain variables

solver/src/main/java/org/chocosolver/solver/variables/impl/IntervalIntVarImpl.java
For such variables, the solver used to track the lower-bound, the upper-bound and the domain size to provide quick access to the domain size. This decision had however a significant impact in terms of memory usage. It requires to have an additional StoredInt per variable and for every bound change, 2 values where saved into the stack.
In this patch, the domain size is no longer stored but computed on demand. In terms of performance, getDomainSize() performs now 2 get() and one subtraction while it used to perform one get(). On the other side it saves one StoredInt, and only one value is saved into the stack when a bound is updated.
After some internal experiments on (packing and scheduling) problems having around 100,000 bounded variables and 50,000 enum variables, this reduces the memory …
=> Stop maintaining the domain size for IntervalIntVarImpl.

solver/src/main/java/org/chocosolver/solver/constraints/nary/nvalue/PropNValue.java
This used to run in O(n). Given the array is read-only, it is ok to sort it and use Arrays.binarySearch() to perform in O(log(n)).
For an internal benchmark with 128 values to watch, contains() was the bottleneck (5% of the service latency), now it is < 1%.
=> Improve PropNValue.contains().

parsers/src/main/java/org/chocosolver/parser/RegParser.java, parsers/src/main/java/org/chocosolver/parser/flatzinc/Flatzinc.java, parsers/src/main/java/org/chocosolver/parser/flatzinc/ast/searches/IntSearch.java, parsers/src/main/java/org/chocosolver/parser/handlers/VarSelHandler.java, parsers/src/main/java/org/chocosolver/parser/xcsp/XCSP.java, parsers/src/test/java/org/chocosolver/parser/RegParserTest.java, solver/src/main/java/org/chocosolver/solver/ParallelPortfolio.java, solver/src/main/java/org/chocosolver/solver/search/strategy/BlackBoxConfigurator.java, solver/src/main/java/org/chocosolver/solver/search/strategy/Search.java, solver/src/main/java/org/chocosolver/solver/search/strategy/SearchParams.java, solver/src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/AbstractFailureBasedVariableSelector.java, solver/src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/AbstractScoreBasedValueSelector.java, solver/src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/ConflictHistorySearch.java, solver/src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/DomOverWDeg.java, solver/src/main/java/org/chocosolver/solver/search/strategy/selectors/variables/DomOverWDegRef.java, solver/src/test/java/org/chocosolver/solver/search/ObjectiveTest.java, solver/src/test/java/org/chocosolver/solver/search/loop/LNSTest.java
The main idea is to define how ties are broken in black-box strategies.
Previously, ties were broken randomly, which is a kind of admission of powerlessness.
I propose, with this PR,  to make possible to declare a tie-breaker if needed or let the default one which is based on  lexical ordering (=variables input order).
Note that this change has few mainly an impact on fresh start when no score are recorded, but as it drives the search to different search space, it may have a huge impact (+ or -) on efficiency.
However, now, we can tweak it.
=> Remove randomness by default of BBox strategies

solver/src/main/java/org/chocosolver/solver/constraints/IIntConstraintFactory.java
The documentation of `increasing` constraint is a copy-paste from the documentation of `decreasing` but has not been fully updated to match the correct description of the constraint (the code of the propagator is correct).
I've also made some minor modifications to `decreasing` docstring to fix minor display issues.
=> Fixed an error in `increasing` constraint documentation and updated `decreasing` constraint documentation

solver/src/main/java/org/chocosolver/solver/constraints/nary/binPacking/PropBinPacking.java, solver/src/test/java/org/chocosolver/solver/constraints/nary/BinPackingTest.java
Fix bin packing's propagator initial propagation (described in #1112)
=> Fix bin packing initial propagation
